name: "Annotate GTNH issue"
description: "Annotate GTNH issue upon their creation"
inputs:
  formdata:
    description: "Parsed form data as a json string"
    required: true
  sections:
    description: "Form data sections to search"
    required: false
    default: "Crash Report"
outputs:
  comments:
    description: "Comment to post on issue."
    value: ${{ steps.run.outputs.comments }}
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Copy requirements for cache key
      shell: bash
      run: cp "${{ github.action_path }}/requirements.txt" "$GITHUB_WORKSPACE/gtnh-requirements.txt"

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('gtnh-requirements.txt') }}

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run
      id: run
      shell: bash
      env:
        INPUT_FORMDATA: ${{ inputs.formdata }}
        INPUT_SECTIONS: ${{ inputs.sections }}
      run: python ${{ github.action_path }}/entrypoint.py
