name: "Annotate GTNH issue"
description: "Annotate GTNH issue upon their creation"
inputs:
  formdata:
    description: "Parsed form data as a json string"
    required: true
  sections:
    description: "Form data sections to search"
    required: false
    default: "Crash Report"
outputs:
  comments:
    description: "Comment to post on issue."
    value: ${{ steps.run.outputs.comments }}   # this line is required for composite actions

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: ${{ github.action_path }}/requirements.txt

    - name: Install dependencies
      shell: bash
      run: |
        pip install \
          "github-action-utils~=1.1.0" \
          "requests<3" \
          "urllib3<2" \
          "packaging>=23.0" \
          "git+https://github.com/GTNewHorizons/DreamAssemblerXXL.git"

    - name: Run
      id: run
      shell: bash
      env:
        INPUT_FORMDATA: ${{ inputs.formdata }}
        INPUT_SECTIONS: ${{ inputs.sections }}
      run: python ${{ github.action_path }}/entrypoint.py
